language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g #&& gulp

after_script:
  - cd ./public
  - git init
  - git config user.name "zhanglingsi"
  - git config user.email "zhanglingsi@aliyun.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://zhanglingsi:${CO_TOKEN}@${CO_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev

env:
 global:
   # Github Pages https://zhanglingsi.github.io/
   - GH_REF: github.com/zhanglingsi/zhanglingsi.github.io.git
   # Coding Pages http://zhanglingsi.coding.me/
   - CO_REF: git.coding.net/zhanglingsi/zhanglingsi.git
